version: '2'
services:
    web:
        build: .
        depends_on:
            - mysqldb
            - redisdb
        volumes:
            - ./website:/home/website:rw
            - ./config:/home/config:rw
            - ./logs:/home/logs
        ports:
            - "22:8022"
            - "80:80"
    mysqldb:
        build: ./database/mysql
        volumes:
            - ./database/mysql/_:/var/lib/mysql
        ports:
            - "3306:3306"
    redisdb:
        build: ./database/redis
        volumes:
            - ./database/redis/_:/var/lib/redis
        ports:
            - "6379:6379"
